apiVersion: v1
kind: Deployment
metadata:
  name : myapp-deployment
spec:
 selector:
    app: my-app
    type: front-end
    
 template:
   metadata:
     labels:
       name: myapp-deployment
   spec:
     containers:
     - name: app
       image: kirtigupta123456/my-app:9
       ports:
       - containerPort: 80
 
